apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: skillhub-minio-data
  namespace: skillhub
  labels:
    app: skillhub-minio
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ssd
  resources:
    requests:
      storage: 500Gi
