import * as fs from 'fs';
import * as path from 'path';
import { AiToolAdapter, SkillEntry, GenerateResult } from './adapter.interface';

export class ClaudeAdapter implements AiToolAdapter {
  readonly name = 'claude';

  async generate(targetDir: string, skills: SkillEntry[], config?: Record<string, any>): Promise<GenerateResult> {
    const dirsCreated: string[] = [];
    const filesCreated: string[] = [];

    // Create Claude-specific directories
    const dirs = [
      path.join(targetDir, '.claude', 'rules'),
      path.join(targetDir, '.claude', 'commands'),
      path.join(targetDir, '.claude', 'skills'),
    ];

    for (const dir of dirs) {
      fs.mkdirSync(dir, { recursive: true });
      dirsCreated.push(dir);
    }

    // Generate CLAUDE.md
    const claudeMdPath = path.join(targetDir, 'CLAUDE.md');
    const claudeMdContent = this.generateClaudeMd(config);
    fs.writeFileSync(claudeMdPath, claudeMdContent, 'utf-8');
    filesCreated.push(claudeMdPath);

    // Generate default rules file
    const rulesPath = path.join(targetDir, '.claude', 'rules', 'project.md');
    fs.writeFileSync(rulesPath, '# Project Rules\n\nGenerated by SkillHub.\n', 'utf-8');
    filesCreated.push(rulesPath);

    // Install skills into .claude/skills/
    for (const skill of skills) {
      const skillDir = path.join(targetDir, '.claude', 'skills', skill.name);
      fs.mkdirSync(skillDir, { recursive: true });
      if (skill.content) {
        const skillFile = path.join(skillDir, 'SKILL.md');
        fs.writeFileSync(skillFile, skill.content, 'utf-8');
        filesCreated.push(skillFile);
      }
    }

    return { filesCreated, dirsCreated };
  }

  getSkillsDir(targetDir: string): string {
    return path.join(targetDir, '.claude', 'skills');
  }

  private generateClaudeMd(config?: Record<string, any>): string {
    const name = config?.projectName || 'Project';
    return `# ${name}\n\nGenerated by SkillHub CLI.\n\n## Rules\n\nSee \`.claude/rules/\` for project-specific rules.\n`;
  }
}
