import * as fs from 'fs';
import * as path from 'path';
import { AiToolAdapter, SkillEntry, GenerateResult } from './adapter.interface';

export class CodebuddyAdapter implements AiToolAdapter {
  readonly name = 'codebuddy';

  async generate(targetDir: string, skills: SkillEntry[], config?: Record<string, any>): Promise<GenerateResult> {
    const dirsCreated: string[] = [];
    const filesCreated: string[] = [];

    // Create CodeBuddy-specific directories
    const dirs = [
      path.join(targetDir, '.codebuddy'),
      path.join(targetDir, '.codebuddy', 'agents'),
    ];

    for (const dir of dirs) {
      fs.mkdirSync(dir, { recursive: true });
      dirsCreated.push(dir);
    }

    // Generate rules.yaml
    const rulesPath = path.join(targetDir, '.codebuddy', 'rules.yaml');
    const content = this.generateRulesYaml(config, skills);
    fs.writeFileSync(rulesPath, content, 'utf-8');
    filesCreated.push(rulesPath);

    // Install skills as agents
    for (const skill of skills) {
      const agentFile = path.join(targetDir, '.codebuddy', 'agents', `${skill.name}.md`);
      if (skill.content) {
        fs.writeFileSync(agentFile, skill.content, 'utf-8');
        filesCreated.push(agentFile);
      }
    }

    return { filesCreated, dirsCreated };
  }

  getSkillsDir(targetDir: string): string {
    return path.join(targetDir, '.codebuddy', 'agents');
  }

  private generateRulesYaml(config?: Record<string, any>, skills?: SkillEntry[]): string {
    const name = config?.projectName || 'Project';
    let yaml = `# ${name} CodeBuddy Rules\n# Generated by SkillHub CLI\n\nproject:\n  name: "${name}"\n`;
    if (skills && skills.length > 0) {
      yaml += `\nagents:\n`;
      for (const skill of skills) {
        yaml += `  - name: "${skill.name}"\n    version: "${skill.version}"\n`;
      }
    }
    return yaml;
  }
}
