import * as fs from 'fs';
import * as path from 'path';
import { AiToolAdapter, SkillEntry, GenerateResult } from './adapter.interface';

export class DefaultAdapter implements AiToolAdapter {
  readonly name = 'default';

  async generate(targetDir: string, skills: SkillEntry[], config?: Record<string, any>): Promise<GenerateResult> {
    const dirsCreated: string[] = [];
    const filesCreated: string[] = [];

    // Create generic .ai/ directory
    const aiDir = path.join(targetDir, '.ai');
    const rulesDir = path.join(aiDir, 'rules');
    const skillsDir = path.join(aiDir, 'skills');

    fs.mkdirSync(rulesDir, { recursive: true });
    fs.mkdirSync(skillsDir, { recursive: true });
    dirsCreated.push(aiDir, rulesDir, skillsDir);

    // Generate README
    const readmePath = path.join(aiDir, 'README.md');
    const name = config?.projectName || 'Project';
    fs.writeFileSync(readmePath, `# ${name} AI Configuration\n\nGenerated by SkillHub CLI.\n`, 'utf-8');
    filesCreated.push(readmePath);

    // Install skills into .ai/skills/
    for (const skill of skills) {
      const skillDir = path.join(skillsDir, skill.name);
      fs.mkdirSync(skillDir, { recursive: true });
      if (skill.content) {
        const skillFile = path.join(skillDir, 'SKILL.md');
        fs.writeFileSync(skillFile, skill.content, 'utf-8');
        filesCreated.push(skillFile);
      }
    }

    return { filesCreated, dirsCreated };
  }

  getSkillsDir(targetDir: string): string {
    return path.join(targetDir, '.ai', 'skills');
  }
}
