import * as fs from 'fs';
import * as path from 'path';
import { AiToolAdapter, SkillEntry, GenerateResult } from './adapter.interface';

export class WindsurfAdapter implements AiToolAdapter {
  readonly name = 'windsurf';

  async generate(targetDir: string, skills: SkillEntry[], config?: Record<string, any>): Promise<GenerateResult> {
    const dirsCreated: string[] = [];
    const filesCreated: string[] = [];

    // Create Windsurf-specific directories
    const rulesDir = path.join(targetDir, '.windsurf', 'rules');
    fs.mkdirSync(rulesDir, { recursive: true });
    dirsCreated.push(rulesDir);

    // Generate .windsurfrules at project root
    const windsurfrules = path.join(targetDir, '.windsurfrules');
    const content = this.generateWindsurfRules(config);
    fs.writeFileSync(windsurfrules, content, 'utf-8');
    filesCreated.push(windsurfrules);

    // Generate rules
    const projectRules = path.join(rulesDir, 'project.md');
    fs.writeFileSync(projectRules, '# Project Rules\n\nGenerated by SkillHub.\n', 'utf-8');
    filesCreated.push(projectRules);

    // Install skills into .windsurf/rules/
    for (const skill of skills) {
      const skillFile = path.join(rulesDir, `${skill.name}.md`);
      if (skill.content) {
        fs.writeFileSync(skillFile, skill.content, 'utf-8');
        filesCreated.push(skillFile);
      }
    }

    return { filesCreated, dirsCreated };
  }

  getSkillsDir(targetDir: string): string {
    return path.join(targetDir, '.windsurf', 'rules');
  }

  private generateWindsurfRules(config?: Record<string, any>): string {
    const name = config?.projectName || 'Project';
    return `# ${name} Windsurf Rules\n\nGenerated by SkillHub CLI.\n`;
  }
}
