import * as fs from 'fs';
import * as path from 'path';
import { AiToolAdapter, SkillEntry, GenerateResult } from './adapter.interface';

export class CursorAdapter implements AiToolAdapter {
  readonly name = 'cursor';

  async generate(targetDir: string, skills: SkillEntry[], config?: Record<string, any>): Promise<GenerateResult> {
    const dirsCreated: string[] = [];
    const filesCreated: string[] = [];

    // Create Cursor-specific directories
    const rulesDir = path.join(targetDir, '.cursor', 'rules');
    fs.mkdirSync(rulesDir, { recursive: true });
    dirsCreated.push(rulesDir);

    // Generate .cursorrules at project root
    const cursorrules = path.join(targetDir, '.cursorrules');
    const content = this.generateCursorRules(config);
    fs.writeFileSync(cursorrules, content, 'utf-8');
    filesCreated.push(cursorrules);

    // Generate rules in .cursor/rules/
    const projectRules = path.join(rulesDir, 'project.md');
    fs.writeFileSync(projectRules, '# Project Rules\n\nGenerated by SkillHub.\n', 'utf-8');
    filesCreated.push(projectRules);

    // Install skills into .cursor/rules/
    for (const skill of skills) {
      const skillFile = path.join(rulesDir, `${skill.name}.md`);
      if (skill.content) {
        fs.writeFileSync(skillFile, skill.content, 'utf-8');
        filesCreated.push(skillFile);
      }
    }

    return { filesCreated, dirsCreated };
  }

  getSkillsDir(targetDir: string): string {
    return path.join(targetDir, '.cursor', 'rules');
  }

  private generateCursorRules(config?: Record<string, any>): string {
    const name = config?.projectName || 'Project';
    return `# ${name} Cursor Rules\n\nGenerated by SkillHub CLI.\n`;
  }
}
