apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-code-usage.fullname" . }}-secret
type: Opaque
stringData:
  postgres-password: {{ .Values.postgres.password | quote }}
  ldap-password: {{ .Values.ldap.bind_password | quote }}
